name: Deploy
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: '63.34.140.33'
        username: 'ubuntu'
        key: ${{ secrets.DEPLOYER_KEY }}
        port: 22
        script: ssh -o StrictHostKeyChecking=no deployer@pprotocol.westeurope.cloudapp.azure.com 'cd pprotocol-account/public/static && GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_website" git pull origin master && cd && ./rails_restart'
