name: DEPLOY

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: deploy the latest code
      run: |
        echo '${{ secrets.DEPLOYER_KEY }}' > deploy.key
        chmod 600 deploy.key
        eval `ssh-agent`
        ssh-add deploy.key
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@ec2-34-251-192-94.eu-west-1.compute.amazonaws.com 'whoami'
