name: DEPLOY

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: deploy the latest code
      run: |
        echo '${{ secrets.DEPLOYER_KEY }}' > deploy.key
        chmod 600 deploy.key
        eval `ssh-agent`
        ssh-add deploy.key
        ssh -J ubuntu@ec2-34-251-192-94.eu-west-1.compute.amazonaws.com deployer@pprotocol.westeurope.cloudapp.azure.com 'cd pprotocol-account/public/static && GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_website" git pull origin master'
