name: DEPLOY

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Install Open VPN
      run: sudo apt-get install openvpn

    - name: Check CA_CRT
      run: echo $CA_CRT

    - name: Connect-VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: ${{ secrets.HOST }}
        FILE_OVPN: 'deploy.ovpn'
        CA_CRT: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV4VENDQTYyZ0F3SUJBZ0lVYXMrK3ZBbGpFWksrSlNqSkxjbGppN0xmRE5jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daVXhDekFKQmdOVkJBWVRBbEpWTVF3d0NnWURWUVFJRXdOTlUwc3hEekFOQmdOVkJBY1RCazF2YzJOdgpkekVRTUE0R0ExVUVDaE1IVlc1cmJtOTNiakVQTUEwR0ExVUVDeE1HUkdWMlQzQnpNUkl3RUFZRFZRUURFd2xzCmIyTmhiR2h2YzNReEVEQU9CZ05WQkNrVEIwVmhjM2xTVTBFeEhqQWNCZ2txaGtpRzl3MEJDUUVXRDJGa2JXbHUKUUd4dlkyRnNhRzl6ZERBZUZ3MHhPVEV3TWpJd09URTNNRGxhRncweU9URXdNVGt3T1RFM01EbGFNSUdWTVFzdwpDUVlEVlFRR0V3SlNWVEVNTUFvR0ExVUVDQk1EVFZOTE1ROHdEUVlEVlFRSEV3Wk5iM05qYjNjeEVEQU9CZ05WCkJBb1RCMVZ1YTI1dmQyNHhEekFOQmdOVkJBc1RCa1JsZGs5d2N6RVNNQkFHQTFVRUF4TUpiRzlqWVd4b2IzTjAKTVJBd0RnWURWUVFwRXdkRllYTjVVbE5CTVI0d0hBWUpLb1pJaHZjTkFRa0JGZzloWkcxcGJrQnNiMk5oYkdodgpjM1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzJHNzJ6czMzWXU5NDU3ZmRmCjg5S0NtVFg2SFJTaXNrN3crRm9XTXFZUEs5Y0tFWDhRQ2NrZEx0UU1BOGZobEF2b2FmUFNPWldGUy9IY0prVjEKMTR1NDEvdkVrcUo0ZjhGUEdTVGwvZ1p6MXdpZmFKUnk2T2xPZXZRYjdGYUgybExGWlpuOVFuTjhSU3lyL2pKLwpyUnRyWW4rOE40QXpmY0EvM2Yrc1JRbWllUUpwTVFmME5OTE1ncVQ4eCtpS1ArbnJxY1gxeEswYVpmVG5DenVFCnJsekp3L1lSVzY3TFlFSWZxTHdzclRnaDRzRXhzbldnOXliQUJRQXp6OHAwTmtFQlluOHAvd3kzNnhGb1l0ZDkKUWNURlBZYmdBOC9TNXMrYlRObCt2ZEZ0WWdCQ2h0bWtKeWVmR3ZqbndYQ0ZrckJTbEFFQmxEclhNWWdjQlh0UwovbzFKQWdNQkFBR2pnZ0VKTUlJQkJUQWRCZ05WSFE0RUZnUVUwZ0xLaXpYMVZZaEtsSFJ1S0Q4UHQwa0VnaEF3CmdkVUdBMVVkSXdTQnpUQ0J5b0FVMGdMS2l6WDFWWWhLbEhSdUtEOFB0MGtFZ2hDaGdadWtnWmd3Z1pVeEN6QUoKQmdOVkJBWVRBbEpWTVF3d0NnWURWUVFJRXdOTlUwc3hEekFOQmdOVkJBY1RCazF2YzJOdmR6RVFNQTRHQTFVRQpDaE1IVlc1cmJtOTNiakVQTUEwR0ExVUVDeE1HUkdWMlQzQnpNUkl3RUFZRFZRUURFd2xzYjJOaGJHaHZjM1F4CkVEQU9CZ05WQkNrVEIwVmhjM2xTVTBFeEhqQWNCZ2txaGtpRzl3MEJDUUVXRDJGa2JXbHVRR3h2WTJGc2FHOXoKZElJVWFzKyt2QWxqRVpLK0pTakpMY2xqaTdMZkROY3dEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFlNUV5Mmh2ejNuSWpQTEkvbnhTRHFvb0RLRmxTUzJEcVlGdGo0Rjg4bFhOQ0ZNamljT2FSCmI3MDYyQjZVclkxQUZNb2pIYTM2MDFnOWNRWm1xY0tRS1JhdG9IbmRzc055RTFhNGRsdmNIM2pyUEZoenJ0aHEKUzYxdWkxelg2QzM1VS9QUlp1ZEVkaGJnQzRScGI2ZTNsVVF5dUtkTzIwUFozK2NhdU5DTGg0UjZoTzBZK3FWVQpyUnMyZi9iU2d4VDdvdCtvbmg4SnVxc0RsUW5DYjlyWlBjMVVxWkdHb0JCMlFUWmg4ZDd6elpNL0pwL2NOeVRTCk1KRnQvVHExYmdQMkpxMVdHWi9UK2VpWm1Id05aeW5JWVVlR1JnV1YzS25PS0JRZGpWdTFYOEpvMWtMMHNtS1oKclRFaWp4K0FoZEZaL0k5alVvTFNxQVFyQ0lhSWtJK3AxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0='
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
        TLS_KEY: ${{ secrets.TLS_KEY }}

    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
