name: DEPLOY

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Install Open VPN
      run: sudo apt-get install openvpn

    - name: Connect-VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: ${{ secrets.HOST }}
        FILE_OVPN: 'deploy.ovpn'
        CA_CRT: ${{ secrets.CA_CRT}}
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
        TLS_KEY: ${{ secrets.TLS_KEY }}

    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
